[package]
name = "tiny-note"
version = "0.1.13"
description = "Tiny Note connected desktop client"
authors = ["Tiny Note"]
edition = "2021"

[lib]
name = "tiny_note_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-process = "2.3.1"
tauri-plugin-dialog = "2.4.0"
tauri-plugin-opener = "2.5.0"
tauri-plugin-notification = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
chrono = { version = "0.4", features = ["serde", "clock"] }
thiserror = "2"
sha2 = "0.10"
md5 = "0.7"
semver = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "stream", "rustls-tls"] }
futures-util = "0.3"
tempfile = "3"
keyring = { version = "3.6.3", features = ["apple-native", "windows-native", "sync-secret-service", "crypto-rust"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]

[profile.release]
strip = "symbols"
lto = "thin"
codegen-units = 1
panic = "abort"
