<script setup lang="ts">
import { Check, Download, ImagePlus, LoaderCircle, X } from 'lucide-vue-next'
import type { ImageGenerationWorkspace } from '../../composables/useImageGenerationWorkspace'

const { workspace } = defineProps<{ workspace: ImageGenerationWorkspace }>()
const { pickerOpen, pickerSearch, visibleNotes, selectedNoteId, insertIntoNote, historyPickerOpen, mode, historyPickerLoading, reusableHistoryAssets, generationAssetUrl, selectHistoryAsset, generationModeLabel, previewItem, closeImagePreview, isSavingAsset, imageSaveTitle, saveImage } = workspace
</script>

<template>
  <div v-if="pickerOpen" class="image-picker-backdrop" @click.self="pickerOpen = false"><section class="image-picker-modal" role="dialog" aria-modal="true"><header><div><strong>插入到笔记</strong><span>选择目标笔记，图片会追加到正文末尾</span></div><button type="button" aria-label="关闭" @click="pickerOpen = false"><X :size="18" /></button></header><div class="image-picker-search"><input v-model="pickerSearch" type="search" placeholder="搜索笔记" /><span>{{ visibleNotes.length }} 条</span></div><div class="image-picker-list"><button v-for="note in visibleNotes" :key="note.id" type="button" :class="{ active: selectedNoteId === note.id }" @click="selectedNoteId = note.id"><span class="image-picker-radio"><Check v-if="selectedNoteId === note.id" :size="12" /></span><span><strong>{{ note.title || '未命名笔记' }}</strong><small>{{ note.contentText || '暂无正文' }}</small></span></button><div v-if="!visibleNotes.length" class="image-picker-empty">没有匹配的笔记</div></div><footer><button type="button" class="image-picker-cancel" @click="pickerOpen = false">取消</button><button type="button" class="image-picker-confirm" :disabled="!selectedNoteId" @click="insertIntoNote">插入图片</button></footer></section></div>
  <div v-if="historyPickerOpen" class="image-picker-backdrop" @click.self="historyPickerOpen = false"><section class="image-history-picker-modal" role="dialog" aria-modal="true" aria-label="选择最近生成的图片"><header><div><strong>选择生成结果</strong><span>{{ mode === 'reference' ? '选择一张加入参考图，可重复打开继续添加' : mode === 'edit' ? '选择一张作为整图编辑的原图' : '选择一张作为局部重绘的原图' }}</span></div><button type="button" aria-label="关闭生成结果选择" @click="historyPickerOpen = false"><X :size="18" /></button></header><div v-if="historyPickerLoading" class="image-history-picker-state"><LoaderCircle class="spinning" :size="18" />正在读取图片…</div><div v-else-if="!reusableHistoryAssets.length" class="image-history-picker-state"><ImagePlus :size="22" />还没有可引用的生成结果</div><div v-else class="image-history-picker-grid"><button v-for="entry in reusableHistoryAssets" :key="entry.asset.id" type="button" :disabled="!generationAssetUrl(entry.asset)" @click="selectHistoryAsset(entry.asset, entry.generation)"><span class="image-history-picker-thumb"><img v-if="generationAssetUrl(entry.asset)" :src="generationAssetUrl(entry.asset)" :alt="entry.generation.prompt" /><LoaderCircle v-else class="spinning" :size="16" /></span><span class="image-history-picker-copy"><strong>{{ entry.generation.prompt }}</strong><small>{{ generationModeLabel(entry.generation.mode) }} · {{ entry.generation.size === 'landscape' ? '横向' : entry.generation.size === 'portrait' ? '纵向' : '1:1' }}</small></span></button></div></section></div>
  <div v-if="previewItem" class="image-preview-backdrop" @click.self="closeImagePreview"><section class="image-preview-modal" role="dialog" aria-modal="true" aria-label="图片大图预览"><header><div><strong>图片预览</strong><span>{{ generationModeLabel(previewItem.generation.mode) }} · {{ previewItem.generation.size === 'landscape' ? '横向' : previewItem.generation.size === 'portrait' ? '纵向' : '1:1' }}</span></div><div><button type="button" class="image-preview-save-button" :disabled="isSavingAsset(previewItem.asset.id)" :aria-busy="isSavingAsset(previewItem.asset.id)" :title="imageSaveTitle(previewItem.asset.id)" @click="saveImage(previewItem.asset, previewItem.generation)"><LoaderCircle v-if="isSavingAsset(previewItem.asset.id)" class="spinning" :size="15" /><Download v-else :size="15" /><span>{{ isSavingAsset(previewItem.asset.id) ? '保存中…' : '保存图片' }}</span></button><button type="button" aria-label="关闭图片预览" @click="closeImagePreview"><X :size="18" /></button></div></header><div class="image-preview-stage"><img :src="previewItem.asset.dataUri" :alt="previewItem.generation.prompt" /></div><footer>{{ previewItem.generation.prompt }}</footer></section></div>
</template>
