import type { BrowserArgs, BrowserItem, BrowserState } from './types'
import type { BrowserHandlerResult } from './planner'

function item(value: Record<string, unknown>): BrowserItem { return value as BrowserItem }
function normalizePath(value = '') { return String(value).replaceAll('\\', '/').replace(/^\/+|\/+$/g, '') }
function parentPath(value = '') { const path = normalizePath(value); const index = path.lastIndexOf('/'); return index < 0 ? '' : path.slice(0, index) }
function entryName(value = '') { const path = normalizePath(value); return path.split('/').pop() || path }

function ensureParents(state: BrowserState, knowledgeBaseId: string | null, relativePath: string, now: string) {
  const parts = normalizePath(relativePath).split('/').filter(Boolean); parts.pop(); let current = ''
  for (const part of parts) { current = current ? `${current}/${part}` : part; if (!state.libraryFiles.some(file => file.knowledgeBaseId === knowledgeBaseId && file.relativePath === current)) state.libraryFiles.push({ knowledgeBaseId, relativePath: current, kind: 'folder', size: 0, modifiedAt: now }) }
}

function entry(file: BrowserItem) { return { name: entryName(file.relativePath), relativePath: file.relativePath, kind: file.kind, size: Number(file.size) || 0, modifiedAt: file.modifiedAt, extension: file.kind === 'file' ? (entryName(file.relativePath).split('.').pop() || '').toLowerCase() : null } }
export function bytesToBase64(bytes: Uint8Array) { let binary = ''; for (const byte of bytes) binary += String.fromCharCode(byte); return globalThis.btoa(binary) }
export function base64ToBytes(value: string) { const binary = globalThis.atob(value); return Uint8Array.from(binary, character => character.charCodeAt(0)) }
function storedText(file: BrowserItem | null | undefined) { if (!file) return ''; if (typeof file.content === 'string') return file.content; if (!file.contentBase64) return ''; try { return new TextDecoder().decode(base64ToBytes(file.contentBase64)) } catch { return '' } }

function uniquePath(state: BrowserState, baseId: string | null, relativePath: string) {
  let finalPath = relativePath; let suffix = 2
  while (state.libraryFiles.some(file => file.knowledgeBaseId === baseId && file.relativePath === finalPath)) { const name = entryName(relativePath); const parent = parentPath(relativePath); const dot = name.lastIndexOf('.'); const stem = dot > 0 ? name.slice(0, dot) : name; const extension = dot > 0 ? name.slice(dot) : ''; finalPath = `${parent ? `${parent}/` : ''}${stem} (${suffix})${extension}`; suffix += 1 }
  return finalPath
}

export async function handleLibraryCommand(command: string, args: BrowserArgs, state: BrowserState, now: string): Promise<BrowserHandlerResult | null> {
  if (command === 'knowledge_base_list') return { result: state.kbs }
  if (command === 'knowledge_base_create') { const base = item({ id: crypto.randomUUID(), category: args.input.category, name: args.input.name, description: args.input.description || '', cover: null, rootPath: '', createdAt: now, updatedAt: now }); state.kbs.push(base); return { result: base } }
  if (command === 'knowledge_base_update') { const base = state.kbs.find(value => value.id === args.id); if (base) Object.assign(base, { name: args.name, description: args.description || '', cover: args.cover, updatedAt: now }); return { result: base || null } }
  if (command === 'knowledge_base_delete') { state.kbs = state.kbs.filter(base => base.id !== args.id); state.notes.forEach(note => { if (note.knowledgeBaseId === args.id) note.knowledgeBaseId = null }); state.libraryFiles = state.libraryFiles.filter(file => file.knowledgeBaseId !== args.id); return { result: null } }
  if (command === 'library_list') { const current = normalizePath(args.relativePath || ''); const query = String(args.search || '').trim().toLowerCase(); const visible = state.libraryFiles.filter(file => file.knowledgeBaseId === args.knowledgeBaseId).filter(file => query ? entryName(file.relativePath).toLowerCase().includes(query) : parentPath(file.relativePath) === current); return { result: visible.sort((a, b) => a.kind === b.kind ? a.relativePath.localeCompare(b.relativePath, undefined, { numeric: true, sensitivity: 'base' }) : a.kind === 'folder' ? -1 : 1).map(entry) } }
  if (command === 'library_create_folder') { const parent = normalizePath(args.relativePath || ''); const folder = args.name.trim(); const relativePath = parent ? `${parent}/${folder}` : folder; if (folder && !folder.includes('/') && !folder.includes('\\') && !state.libraryFiles.some(file => file.knowledgeBaseId === args.knowledgeBaseId && file.relativePath === relativePath)) { ensureParents(state, args.knowledgeBaseId, relativePath, now); state.libraryFiles.push({ knowledgeBaseId: args.knowledgeBaseId, relativePath, kind: 'folder', size: 0, modifiedAt: now }) } return { result: null } }
  if (command === 'library_write_file' || command === 'library_write_file_bytes') { const relativePath = normalizePath(args.relativePath); ensureParents(state, args.knowledgeBaseId, relativePath, now); const finalPath = uniquePath(state, args.knowledgeBaseId, relativePath); if (command === 'library_write_file') { const content = String(args.content || ''); state.libraryFiles.push({ knowledgeBaseId: args.knowledgeBaseId, relativePath: finalPath, kind: 'file', size: content.length, modifiedAt: now, content }) } else { const bytes = Array.isArray(args.content) ? Uint8Array.from(args.content) : base64ToBytes(args.contentBase64 || ''); state.libraryFiles.push({ knowledgeBaseId: args.knowledgeBaseId, relativePath: finalPath, kind: 'file', size: bytes.length, modifiedAt: now, contentBase64: bytesToBase64(bytes) }) } return { result: entry(state.libraryFiles.at(-1)!) } }
  if (command === 'library_import_url') { if (!/^https?:\/\//i.test(args.url.trim())) throw new Error('只支持 HTTP 或 HTTPS 地址'); const response = await fetch(args.url); if (!response.ok) throw new Error('URL 导入失败'); const bytes = new Uint8Array(await response.arrayBuffer()); if (bytes.length > 5 * 1024 * 1024) throw new Error('远程文件不能超过 5MB'); const url = new URL(args.url); const finalPath = normalizePath(args.relativePath || url.pathname.split('/').filter(Boolean).pop() || 'imported.md'); ensureParents(state, args.knowledgeBaseId, finalPath, now); state.libraryFiles.push({ knowledgeBaseId: args.knowledgeBaseId, relativePath: finalPath, kind: 'file', size: bytes.length, modifiedAt: now, contentBase64: bytesToBase64(bytes) }); return { result: entry(state.libraryFiles.at(-1)!) } }
  if (command === 'library_rename') { const oldPath = normalizePath(args.relativePath); const nextName = args.newName.trim(); const target = `${parentPath(oldPath) ? `${parentPath(oldPath)}/` : ''}${nextName}`; const exists = state.libraryFiles.some(file => file.knowledgeBaseId === args.knowledgeBaseId && file.relativePath === target); if (!exists && nextName && !nextName.includes('/') && !nextName.includes('\\')) state.libraryFiles.filter(file => file.knowledgeBaseId === args.knowledgeBaseId && (file.relativePath === oldPath || file.relativePath.startsWith(`${oldPath}/`))).forEach(file => { file.relativePath = target + file.relativePath.slice(oldPath.length) }); return { result: null } }
  if (command === 'library_move_to_trash') { const target = normalizePath(args.relativePath); state.libraryFiles = state.libraryFiles.filter(file => !(file.knowledgeBaseId === args.knowledgeBaseId && (file.relativePath === target || file.relativePath.startsWith(`${target}/`)))); return { result: null } }
  if (command === 'library_preview') { const target = normalizePath(args.relativePath); const file = state.libraryFiles.find(value => value.knowledgeBaseId === args.knowledgeBaseId && value.relativePath === target); const extension = (entryName(target).split('.').pop() || '').toLowerCase(); const kind = ['html', 'htm'].includes(extension) ? 'html' : extension || 'text'; const mimes: Record<string, string> = { png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif', webp: 'image/webp', svg: 'image/svg+xml' }; return { result: file ? mimes[extension] ? { title: entryName(target), kind: 'image', mimeType: mimes[extension], content: `data:${mimes[extension]};base64,${file.contentBase64 || ''}` } : ['pdf', 'epub'].includes(extension) ? { title: entryName(target), kind: 'unsupported', mimeType: 'application/octet-stream', content: '该文件已保存，但当前版本暂不提供预览。' } : { title: entryName(target), kind, mimeType: kind === 'html' ? 'text/html' : 'text/plain', content: storedText(file) } : null } }
  return null
}
