version: '1.0'
name: pipeline-20260608
displayName: pipeline-20260608
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - dev
stages:
  - name: stage-bb40c76e
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor:
      - ynx520
    steps:
      - step: build@rust
        name: build_rust
        displayName: Rust 构建
        rustVersion: '1.89'
        commands:
          - cargo build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./target
        caches: []
        notify: []
        strategy:
          retry: '0'
